scenario:
  name: obstacle_split_merge
  goals:
    - robot_id: 0
      x: 8.0
      y: 2.5
      z: 1.0
    - robot_id: 1
      x: 8.0
      y: -2.5
      z: 1.0
    - robot_id: 2
      x: 8.0
      y: 0.0
      z: 1.0
